Rename to "Meltano Singer SDK"
meltano/sdk pull request #1053
Opened 2022-10-07 19:55 UTC by DouweM

2022-10-07 20:30 UTC, edgarrmondragon requested changes

2022-10-07 20:30 UTC, edgarrmondragon commented on docs/index.rst
>  =======================================
```suggestion
==================
```

2022-10-07 21:12 UTC, tayloramurphy approved these changes

2022-10-07 21:15 UTC, edgarrmondragon approved these changes

2022-10-10 14:34 UTC, afolson approved these changes

2022-10-10 19:26 UTC, merged