feat: Build empty cookiecutters and run lint task during CI
meltano/sdk pull request #1410
Opened 2023-02-10 09:35 UTC by flexponsive

Related to #993

Adds a Github Action to build empty cookiecutters from [replay files](https://cookiecutter.readthedocs.io/en/stable/advanced/replay.html) and runs lint task against the (empty) cookiecutter. Additionally, a script which creates and lints in one step for developer convenience while working on cookiecutter templates.

This PR also includes various fixes (method signatures, import sorting, docstrings etc.) demanded by the linter for the case of a tap with REST stream type and API Key authentication method.

2023-02-10 20:38 UTC, tayloramurphy commented
Thanks for the PR @flexponsive - looks like we've got some engineers assigned as reviewers who will get back to you likely sometime next week!

2023-02-10 20:40 UTC, edgarrmondragon commented
Hey @flexponsive! Looks like flake8 is complaining. Let me know when this is ready to be reviewed 🙂

2023-02-12 20:08 UTC, flexponsive commented
@edgarrmondragon I have updated the PR and description. Github does not show the results from the E2E-Tests of cookiecutters here in the PR, they are available here:
- [tap, rest, API key](https://github.com/flexponsive/meltano-sdk/actions/runs/4156469784/jobs/7190280635)
- [target, per record](https://github.com/flexponsive/meltano-sdk/actions/runs/4156469784/jobs/7190280688) - does not actually lint due to #360

2023-02-13 23:48 UTC, aaronsteers commented
@flexponsive - First of all - _thank you_ for creating this PR! 

What do you think of adding a step to upload the generated projects using GitHub artifacts, if not already doing so?

https://github.com/actions/upload-artifact

```yml
- uses: actions/upload-artifact@v3
  with:
    name: my-artifact
    path: path/to/artifact/world.txt
```

2023-02-14 00:04 UTC, edgarrmondragon requested changes
Hey @flexponsive. A few comments and suggestions. The bash script is good for an initial iteration of this but we should probably (not necessarily) in this PR port it to Nox since that's where we centralize dev tasks.

2023-02-14 00:04 UTC, edgarrmondragon commented on .github/workflows/cookiecutter-e2e.yml
> +        cache-dependency-path: 'poetry.lock'
Probably doesn't make sense to use the package's `poetry.lock` as cache key for the templates, e.g. the templates cache could need to refreshed even if `poetry.lock` hasn`t changed.
```suggestion
```

2023-02-14 00:04 UTC, edgarrmondragon commented on .github/workflows/cookiecutter-e2e.yml
> +
Extra line break

```suggestion
```

2023-02-14 00:04 UTC, edgarrmondragon commented on e2e-tests/cookiecutters/test_cookiecutter.sh
> +    poetry install
Is this maybe missing a `poetry lock` step?

2023-02-14 09:14 UTC, flexponsive commented
Thank you for the fast feedback and improvements to the PR!

@edgarrmondragon I accepted the suggestions and believe the issues you raised are fixed. I agree that it would be a good idea in the future to migrate from the bash script to tox but probably outside the scope of this PR.

@aaronsteers build artifact upload has been added too

Sample run: https://github.com/flexponsive/meltano-sdk/actions/runs/4172051621

2023-02-14 16:32 UTC, aaronsteers commented
> build artifact upload has been added too

Nice! Thank you!

2023-02-14 22:39 UTC, edgarrmondragon commented
Reviewing now...

2023-02-14 22:45 UTC, edgarrmondragon approved these changes

2023-02-14 23:59 UTC, edgarrmondragon approved these changes

2023-02-15 00:03 UTC, merged

2023-02-15 00:03 UTC, edgarrmondragon commented
Thanks @flexponsive!