fix: force write last state message
meltano/sdk pull request #1708
Opened 2023-05-16 15:56 UTC by kgpayne

2023-05-16 17:54 UTC, aaronsteers commented
@kgpayne - I did some digging and found that `Stream.finalize_state_progress_markers` actually calls a black box `finalize_state_progress_markers()`, which does not return a value.

https://github.com/meltano/sdk/blob/5ff3f4529b7e02831e38f2185df6342d06da21a7/singer_sdk/helpers/_state.py#L248-L270

Probably more scope than is needed, given that sending an extra `STATE` message is relatively harmless, but a long-term fix might migrate the helper function directly into the class - allowing it then to update the `Stream._is_state_flushed` property. Alternatively, the helper function could return a boolean value indicating "True" if changes are applied. Complicating matters (and expanding scope) is the fact that many write operations in the above helper function are not behind conditional checks.

Regarding performance of this operation, at least this operation is once-per-state-finalization-option and not once-per-record-write. Otherwise this would be more high-stakes code to update, performance wise. 🤷

2023-05-16 18:26 UTC, kgpayne commented
@aaronsteers the root cause was indeed missing `self._is_state_flushed = False` snippets. We are not marking state as flushable after calling `finalize_state_progress_markers`, which meant the final calls in stream and tap to `_write_state_message()` were skipped by the `if` statement in that method.

For now I was able to 'fix' the issue @laurentS is seeing in `tap-github` by i) setting `self._is_state_flushed = False` after every call to the `finalize_state_progress_markers` helper function (as state _may_ have changed) and ii) deduping in `Stream._write_state_message()` to eliminate duplicates. Its not elegant, but I wanted to verify I understood the root cause 🙂

Re: a refactor: we use the `finalize_state_progress_markers` helper function within the stream and the `Stream.finalize_state_progress_markers` from the Tap. Agree this could and probably should be refactored so that the `Stream.finalize_state_progress_markers` is the only one used, allowing us to toggle `_is_state_flushed` inline. Will keep hacking at this PR tomorrow.

FYI @edgarrmondragon - open to all feedback and suggestions 🙂

2023-05-16 18:37 UTC, aaronsteers commented
@kgpayne - Yeah, nice. Agreed with all the above. 👍

2023-05-17 16:36 UTC, edgarrmondragon requested changes

2023-05-17 16:36 UTC, edgarrmondragon commented on singer_sdk/streams/core.py
> +    def _finalize_state_progress_markers(
Can we rename this? There's now three functions with the same name and signature, so it's hard to tell what each of them is doing:

* `singer_sdk.helpers._state.finalize_state_progress_markers`
* `singer_sdk.streams.core.Stream.finalize_state_progress_markers`
* `singer_sdk.streams.core.Stream._finalize_state_progress_markers`

2023-05-17 16:36 UTC, edgarrmondragon commented on singer_sdk/streams/core.py
> +        self._write_state_message()
Is it possible to call this outside of this scope. This method should _prepare_ the state to be emitted but it shouldn't actually write the message.

2023-05-22 09:17 UTC, laurentS commented
@kgpayne @edgarrmondragon @aaronsteers is it worth bringing some form of the test that fails in `tap-github` upstream in the sdk to avoid regressions like this in the future? I'm thinking some simplified variant of [this one](https://github.com/MeltanoLabs/tap-github/pull/164/files#diff-4ad85a3deb7265065f80b3a0b6093a1dc32975536e497c12a5af0425f4d346c9R105).

2023-05-23 00:28 UTC, edgarrmondragon commented
> @kgpayne @edgarrmondragon @aaronsteers is it worth bringing some form of the test that fails in `tap-github` upstream in the sdk to avoid regressions like this in the future? I'm thinking some simplified variant of [this one](https://github.com/MeltanoLabs/tap-github/pull/164/files#diff-4ad85a3deb7265065f80b3a0b6093a1dc32975536e497c12a5af0425f4d346c9R105).

@laurentS I agree, we should take the opportunity to guard against future regressions 👍

2023-07-14 18:04 UTC, edgarrmondragon commented on singer_sdk/streams/core.py
> +        self._write_state_message()
Nevermind

2023-07-14 18:08 UTC, edgarrmondragon commented on singer_sdk/streams/core.py
> +    def _finalize_state_progress_markers(
Done in 9c353cce4b1b2d886d4463b9ef24630f932c76fe

2023-07-14 18:36 UTC, edgarrmondragon approved these changes
Ken's work is 👌 here. I only an automatic test so I'm confident merging.

2023-07-14 18:36 UTC, merged