docs: fix incompatible JSON in Stream Maps page and add meltano.yml tabs
meltano/sdk pull request #1756
Opened 2023-06-08 05:13 UTC by mjsqu

Resolves #797

2023-06-08 05:26 UTC, mjsqu commented
Quick link to the changed page:
https://meltano-sdk--1756.org.readthedocs.build/en/1756/stream_maps.html

2023-06-08 05:33 UTC, mjsqu commented
Just shifted the meltano.yml tabs first, makes more sense as the tabs with the comments are displayed first - the JSON without comments can be viewed optionally

2023-06-08 12:43 UTC, pnadolny13 commented
@mjsqu these tabs look so good, thanks for the PR!

The only thing I'm still unclear on is null handling in the meltano.yml files. I know theres an option to include `__NULL__` or I guess [in my case](https://github.com/meltano/squared/blob/e28db7d44d33c8469d39d0a0cb0913ab33ed587b/data/extract/mappers.meltano.yml#L11) I ended up leaving it empty to represent null instead of the actual `null` keyword. @edgarrmondragon can you clarify the best way to represent these in the docs?

2023-06-19 20:28 UTC, edgarrmondragon requested changes

2023-06-19 20:28 UTC, edgarrmondragon commented on pyproject.toml
> +sphinx-inline-tabs = {version = "^2023.4.21"}
To make sure this isn't pulled every time someones installs the Singer SDK:

```suggestion
sphinx-inline-tabs = {version = "^2023.4.21", optional = true}
```

You'll also have to run `poetry lock` and push the updated `poetry.lock` file.

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    customer_id: null
```suggestion
    customer_id: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    email: null
```suggestion
    email: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +  addresses: null
```suggestion
  addresses: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    email: null
```suggestion
    email: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +  __else__: null
```suggestion
  __else__: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    __else__: null
```suggestion
    __else__: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    full_name: null
```suggestion
    email: __NULL__
    full_name: __NULL__
```

2023-06-19 20:28 UTC, edgarrmondragon commented on docs/stream_maps.md
> +    __else__: null
```suggestion
    __else__: __NULL__
```

2023-06-19 20:29 UTC, edgarrmondragon commented
> @mjsqu these tabs look so good, thanks for the PR!
> 
> The only thing I'm still unclear on is null handling in the meltano.yml files. I know theres an option to include `__NULL__` or I guess [in my case](https://github.com/meltano/squared/blob/e28db7d44d33c8469d39d0a0cb0913ab33ed587b/data/extract/mappers.meltano.yml#L11) I ended up leaving it empty to represent null instead of the actual `null` keyword. @edgarrmondragon can you clarify the best way to represent these in the docs?

@pnadolny13 good catch! It's probably just better to use `__NULL__` in all the `meltano.yml` examples to save users any potential issues around Meltano's handling of null values.

2023-06-20 08:08 UTC, mjsqu commented
Having some problems running `poetry lock`:
![image](https://github.com/meltano/sdk/assets/17741131/a6901864-daa2-49ba-bd4a-4bdab60ab6ae)

2023-06-20 08:13 UTC, mjsqu commented
Uh - I thought a poetry lock run was suggested, but I can't find that comment now 😆

2023-06-20 16:55 UTC, edgarrmondragon commented
> Uh - I thought a poetry lock run was suggested, but I can't find that comment now 😆

Lol, it's here: https://github.com/meltano/sdk/pull/1756#discussion_r1234452456

> Having some problems running `poetry lock`: ![image](https://user-images.githubusercontent.com/17741131/247049362-a6901864-daa2-49ba-bd4a-4bdab60ab6ae.png)

Oh, bummer. The tabs plugin requires Python 3.8+ 😭. That means https://github.com/meltano/sdk/issues/1659 is a blocker for this.

2023-06-21 00:07 UTC, edgarrmondragon commented
> Oh, bummer. The tabs plugin requires Python 3.8+ 😭. That means #1659 is a blocker for this.

On second thought, RTD uses Python 3.11 to build the docs so using an env marker for the dependency should be fine.

2023-06-21 00:11 UTC, edgarrmondragon approved these changes

2023-06-21 19:48 UTC, merged