draft: add ability to do list comprehensions in stream map expressions
meltano/sdk pull request #2003
Opened 2023-10-07 20:48 UTC by haleemur

2023-10-07 21:49 UTC, edgarrmondragon commented
Hey @haleemur,

Thanks for contributing! Ping me when this is ready to review 🙂

2023-10-08 20:06 UTC, tayloramurphy commented
Thanks for the contribution @haleemur ! @edgarrmondragon can you open a separate issue for adding this as an example to https://sdk.meltano.com/en/latest/stream_maps.html ?

2023-10-09 17:02 UTC, edgarrmondragon requested changes

2023-10-09 17:02 UTC, edgarrmondragon commented on tests/core/test_simpleeval.py
This test file was also vendored, so it can probably be removed if we're going forward adding the dependency.

2023-10-10 21:20 UTC, haleemur commented
@edgarrmondragon 

I'll take a look at why mypy is complaining on 3.8, but otherwise, I think the PR is ready.

When looking at the benchmark run in the workflows a significant improvement is noted (likely due to parsing only once)

* [current branch median](https://github.com/meltano/sdk/actions/runs/6474806593/job/17580538748?pr=2003#step:7:532): 174.63
* [main branch median](https://github.com/meltano/sdk/actions/runs/6474067943/job/17578183393#step:7:624): 656.25
* the benchmark median-duration is 3.7 times shorter


Locally run benchmarks reveal a similar story.

`meltano:main` locally run benchmark
```
------------------------------------------------------- benchmark: 1 tests ------------------------------------------------------
Name (time in ms)                         Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------
test_bench_simple_map_transforms     318.3243  320.8534  319.9556  0.9875  320.2287  1.1652       1;0  3.1254       5           1
---------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================= 1 passed, 473 skipped, 2 deselected, 8 warnings in 3.55s =============================================================

```

`haleemur:simpleeval-compound-data-types` locally run benchmark
```
----------------------------------------------------- benchmark: 1 tests -----------------------------------------------------
Name (time in ms)                        Min      Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------
test_bench_simple_map_transforms     84.7507  86.4868  85.4988  0.5254  85.5117  0.7484       3;0  11.6961      12           1
------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================= 1 passed, 390 skipped, 2 deselected, 8 warnings in 2.48s =============================================================
```

2023-10-10 23:02 UTC, edgarrmondragon approved these changes
This is amazing. Thanks @haleemur!

2023-10-10 23:07 UTC, merged